-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clients
(
    client_id integer NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    address character varying(50) COLLATE pg_catalog."default" NOT NULL,
    city character varying(50) COLLATE pg_catalog."default" NOT NULL,
    state character(2) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    CONSTRAINT clients_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public.invoices
(
    invoices_id integer NOT NULL,
    "number" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    client_id integer NOT NULL,
    invoice_total numeric(9, 0) NOT NULL,
    payment_total numeric(9, 0) NOT NULL DEFAULT 0.00,
    invoice_date date NOT NULL,
    due_date date NOT NULL,
    payment_date date,
    CONSTRAINT invoices_pkey PRIMARY KEY (invoices_id)
);

CREATE TABLE IF NOT EXISTS public.payment_methods
(
    payment_method_id integer NOT NULL DEFAULT nextval('payment_methods_payment_method_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT payment_methods_pkey PRIMARY KEY (payment_method_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id serial NOT NULL,
    client_id integer NOT NULL,
    invoice_id integer NOT NULL,
    date date NOT NULL,
    amount numeric(9, 2) NOT NULL,
    payment_methods integer NOT NULL,
    PRIMARY KEY (payment_id)
);

ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT fk_client_id FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk_client_id FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk_invoice_id FOREIGN KEY (payment_id)
    REFERENCES public.payments (payment_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk_payment_method FOREIGN KEY (payment_methods)
    REFERENCES public.payment_methods (payment_method_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;