# Generated by Django 5.2.8 on 2026-02-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('unpublished', 'unpublished')], default='unpublished', max_length=100),
        ),
    ]
